// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * Hotkey is a combination of modifiers and key to trigger an event
 */
export class Hotkey {

    /** Creates a new Hotkey instance. */
    constructor($$source: Partial<Hotkey> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Hotkey instance from a string or object.
     */
    static createFrom($$source: any = {}): Hotkey {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Hotkey($$parsedSource as Partial<Hotkey>);
    }
}
