// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class NotionDataSourceDetail {
    "id": string;
    "name": string;
    "properties": { [_: string]: PropertyObj };

    /** Creates a new NotionDataSourceDetail instance. */
    constructor($$source: Partial<NotionDataSourceDetail> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("properties" in $$source)) {
            this["properties"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotionDataSourceDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): NotionDataSourceDetail {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("properties" in $$parsedSource) {
            $$parsedSource["properties"] = $$createField2_0($$parsedSource["properties"]);
        }
        return new NotionDataSourceDetail($$parsedSource as Partial<NotionDataSourceDetail>);
    }
}

export class NotionDataSourceList {
    "results": NotionDataSourceSummary[];

    /** Creates a new NotionDataSourceList instance. */
    constructor($$source: Partial<NotionDataSourceList> = {}) {
        if (!("results" in $$source)) {
            this["results"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotionDataSourceList instance from a string or object.
     */
    static createFrom($$source: any = {}): NotionDataSourceList {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField0_0($$parsedSource["results"]);
        }
        return new NotionDataSourceList($$parsedSource as Partial<NotionDataSourceList>);
    }
}

export class NotionDataSourceSummary {
    "id": string;
    "name": string;
    "parent_database_id"?: string;

    /** Creates a new NotionDataSourceSummary instance. */
    constructor($$source: Partial<NotionDataSourceSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotionDataSourceSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): NotionDataSourceSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NotionDataSourceSummary($$parsedSource as Partial<NotionDataSourceSummary>);
    }
}

export class PropertyObj {
    "id": string;
    "name": string;
    "type": string;

    /** Creates a new PropertyObj instance. */
    constructor($$source: Partial<PropertyObj> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PropertyObj instance from a string or object.
     */
    static createFrom($$source: any = {}): PropertyObj {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PropertyObj($$parsedSource as Partial<PropertyObj>);
    }
}

export class TaskInformation {
    "title": string;
    "date": string | null;

    /** Creates a new TaskInformation instance. */
    constructor($$source: Partial<TaskInformation> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("date" in $$source)) {
            this["date"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskInformation instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskInformation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskInformation($$parsedSource as Partial<TaskInformation>);
    }
}

// Private type creation functions
const $$createType0 = PropertyObj.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = NotionDataSourceSummary.createFrom;
const $$createType3 = $Create.Array($$createType2);
