// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class TaskInformation {
    "title": string;
    "date": string | null;

    /** Creates a new TaskInformation instance. */
    constructor($$source: Partial<TaskInformation> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("date" in $$source)) {
            this["date"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskInformation instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskInformation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskInformation($$parsedSource as Partial<TaskInformation>);
    }
}
