// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetSettings(): Promise<$models.FrontendSettings> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3034808949) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function LoadSettings(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3298483949) as any;
    return $resultPromise;
}

export function SaveSettings(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2662658340) as any;
    return $resultPromise;
}

/**
 * Internal version that only writes to file
 */
export function SaveSettingsInternal(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2120971533) as any;
    return $resultPromise;
}

export function SetApp(app: application$0.App | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(72634023, app) as any;
    return $resultPromise;
}

export function UpdateSettings(raw: { [_: string]: any }): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2846770304, raw) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.FrontendSettings.createFrom;
