// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * RegisterWindow Register a window by ID
 */
export function RegisterWindow(id: string, win: application$0.WebviewWindow | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2953663024, id, win) as any;
    return $resultPromise;
}

/**
 * ToggleVisibility Toggle visibility of a window by ID
 */
export function ToggleVisibility(id: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4127976233, id) as any;
    return $resultPromise;
}
