// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class FrontendSettings {
    "notion_data_source_id": string;
    "use_open_ai": boolean;
    "theme": string;
    "launch_on_startup": boolean;
    "hotkey": string;
    "has_notion_secret": boolean;
    "has_openai_key": boolean;
    "date_property_id": string;
    "date_property_name": string;

    /** Creates a new FrontendSettings instance. */
    constructor($$source: Partial<FrontendSettings> = {}) {
        if (!("notion_data_source_id" in $$source)) {
            this["notion_data_source_id"] = "";
        }
        if (!("use_open_ai" in $$source)) {
            this["use_open_ai"] = false;
        }
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("launch_on_startup" in $$source)) {
            this["launch_on_startup"] = false;
        }
        if (!("hotkey" in $$source)) {
            this["hotkey"] = "";
        }
        if (!("has_notion_secret" in $$source)) {
            this["has_notion_secret"] = false;
        }
        if (!("has_openai_key" in $$source)) {
            this["has_openai_key"] = false;
        }
        if (!("date_property_id" in $$source)) {
            this["date_property_id"] = "";
        }
        if (!("date_property_name" in $$source)) {
            this["date_property_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FrontendSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): FrontendSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FrontendSettings($$parsedSource as Partial<FrontendSettings>);
    }
}
