// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ClearOpenAIKey(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(836461708) as any;
    return $resultPromise;
}

export function GetSettings(): Promise<$models.FrontendSettings> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1299891847) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function LoadSettings(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3851458195) as any;
    return $resultPromise;
}

export function SaveNotionToken(token: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1686561367, token) as any;
    return $resultPromise;
}

export function SaveOpenAIKey(key: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2201247664, key) as any;
    return $resultPromise;
}

export function SaveSettings(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(194780622) as any;
    return $resultPromise;
}

export function SetApp(app: application$0.App | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2639386645, app) as any;
    return $resultPromise;
}

export function UpdateSettingsFromFrontend(raw: { [_: string]: any }): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2794697606, raw) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.FrontendSettings.createFrom;
