package settingsservice

import "golang.design/x/hotkey"

// Mapping strings to modifiers
var modMap = map[string]hotkey.Modifier{
	"ctrl":   hotkey.ModCtrl,
	"shift":  hotkey.ModShift,
	"option": hotkey.ModOption,
	"cmd":    hotkey.ModCmd,
}

// Mapping strings to keys
var keyMap = map[string]hotkey.Key{
	"space": hotkey.KeySpace,
	"a":     hotkey.KeyA,
	"b":     hotkey.KeyB,
	"c":     hotkey.KeyC,
	"d":     hotkey.KeyD,
	"e":     hotkey.KeyE,
	"f":     hotkey.KeyF,
	"g":     hotkey.KeyG,
	"h":     hotkey.KeyH,
	"i":     hotkey.KeyI,
	"j":     hotkey.KeyJ,
	"k":     hotkey.KeyK,
	"l":     hotkey.KeyL,
	"m":     hotkey.KeyM,
	"n":     hotkey.KeyN,
	"o":     hotkey.KeyO,
	"p":     hotkey.KeyP,
	"q":     hotkey.KeyQ,
	"r":     hotkey.KeyR,
	"s":     hotkey.KeyS,
	"t":     hotkey.KeyT,
	"u":     hotkey.KeyU,
	"v":     hotkey.KeyV,
	"w":     hotkey.KeyW,
	"x":     hotkey.KeyX,
	"y":     hotkey.KeyY,
	"z":     hotkey.KeyZ,
	"0":     hotkey.Key0,
	"1":     hotkey.Key1,
	"2":     hotkey.Key2,
	"3":     hotkey.Key3,
	"4":     hotkey.Key4,
	"5":     hotkey.Key5,
	"6":     hotkey.Key6,
	"7":     hotkey.Key7,
	"8":     hotkey.Key8,
	"9":     hotkey.Key9,
	"dlt":   hotkey.KeyDelete,
	"esc":   hotkey.KeyEscape,
	"down":  hotkey.KeyDown,
	"up":    hotkey.KeyUp,
	"left":  hotkey.KeyLeft,
	"right": hotkey.KeyRight,
	"enter": hotkey.KeyReturn,
	"tab":   hotkey.KeyTab,
	"F1":    hotkey.KeyF1,
	"F2":    hotkey.KeyF2,
	"F3":    hotkey.KeyF3,
	"F4":    hotkey.KeyF4,
	"F5":    hotkey.KeyF5,
	"F6":    hotkey.KeyF6,
	"F7":    hotkey.KeyF7,
	"F8":    hotkey.KeyF8,
	"F9":    hotkey.KeyF9,
	"F10":   hotkey.KeyF10,
	"F11":   hotkey.KeyF11,
	"F12":   hotkey.KeyF12,
	"F13":   hotkey.KeyF13,
	"F14":   hotkey.KeyF14,
	"F15":   hotkey.KeyF15,
	"F16":   hotkey.KeyF16,
	"F17":   hotkey.KeyF17,
	"F18":   hotkey.KeyF18,
	"F19":   hotkey.KeyF19,
	"F20":   hotkey.KeyF20,
}

// Reverse maps
var revModMap = map[hotkey.Modifier]string{
	hotkey.ModCtrl:   "ctrl",
	hotkey.ModShift:  "shift",
	hotkey.ModOption: "option",
	hotkey.ModCmd:    "cmd",
}

var revKeyMap = map[hotkey.Key]string{
	hotkey.KeySpace:  "space",
	hotkey.KeyA:      "a",
	hotkey.KeyB:      "b",
	hotkey.KeyC:      "c",
	hotkey.KeyD:      "d",
	hotkey.KeyE:      "e",
	hotkey.KeyF:      "f",
	hotkey.KeyG:      "g",
	hotkey.KeyH:      "h",
	hotkey.KeyI:      "i",
	hotkey.KeyJ:      "j",
	hotkey.KeyK:      "k",
	hotkey.KeyL:      "l",
	hotkey.KeyM:      "m",
	hotkey.KeyN:      "n",
	hotkey.KeyO:      "o",
	hotkey.KeyP:      "p",
	hotkey.KeyQ:      "q",
	hotkey.KeyR:      "r",
	hotkey.KeyS:      "s",
	hotkey.KeyT:      "t",
	hotkey.KeyU:      "u",
	hotkey.KeyV:      "v",
	hotkey.KeyW:      "w",
	hotkey.KeyX:      "x",
	hotkey.KeyY:      "y",
	hotkey.KeyZ:      "z",
	hotkey.Key0:      "0",
	hotkey.Key1:      "1",
	hotkey.Key2:      "2",
	hotkey.Key3:      "3",
	hotkey.Key4:      "4",
	hotkey.Key5:      "5",
	hotkey.Key6:      "6",
	hotkey.Key7:      "7",
	hotkey.Key8:      "8",
	hotkey.Key9:      "9",
	hotkey.KeyDelete: "dlt",
	hotkey.KeyEscape: "esc",
	hotkey.KeyDown:   "down",
	hotkey.KeyUp:     "up",
	hotkey.KeyLeft:   "left",
	hotkey.KeyRight:  "right",
	hotkey.KeyReturn: "enter",
	hotkey.KeyTab:    "tab",
	hotkey.KeyF1:     "F1",
	hotkey.KeyF2:     "F2",
	hotkey.KeyF3:     "F3",
	hotkey.KeyF4:     "F4",
	hotkey.KeyF5:     "F5",
	hotkey.KeyF6:     "F6",
	hotkey.KeyF7:     "F7",
	hotkey.KeyF8:     "F8",
	hotkey.KeyF9:     "F9",
	hotkey.KeyF10:    "F10",
	hotkey.KeyF11:    "F11",
	hotkey.KeyF12:    "F12",
	hotkey.KeyF13:    "F13",
	hotkey.KeyF14:    "F14",
	hotkey.KeyF15:    "F15",
	hotkey.KeyF16:    "F16",
	hotkey.KeyF17:    "F17",
	hotkey.KeyF18:    "F18",
	hotkey.KeyF19:    "F19",
	hotkey.KeyF20:    "F20",
}
