// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function DisableLaunchAtLogin(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1682952237) as any;
    return $resultPromise;
}

export function EnableLaunchAtLogin(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3681000516) as any;
    return $resultPromise;
}

export function IsEnabled(): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3912406963) as any;
    return $resultPromise;
}
