// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class Identity {
    "UserID": string;
    "AuthToken": string;

    /** Creates a new Identity instance. */
    constructor($$source: Partial<Identity> = {}) {
        if (!("UserID" in $$source)) {
            this["UserID"] = "";
        }
        if (!("AuthToken" in $$source)) {
            this["AuthToken"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Identity instance from a string or object.
     */
    static createFrom($$source: any = {}): Identity {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Identity($$parsedSource as Partial<Identity>);
    }
}
